import mongoose from 'mongoose';
import dotenv from 'dotenv';
import College from '../models/College.js';
import Book from '../models/Book.js';
import User from '../models/User.js';

dotenv.config();

const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB Atlas');

    // Clear existing data
    await College.deleteMany({});
    await Book.deleteMany({});
    await User.deleteMany({});
    console.log('Cleared existing data');

    // Create colleges
    const colleges = await College.insertMany([
      {
        name: 'Indian Institute of Technology Madras',
        code: 'IITM',
        state: 'Tamil Nadu',
        city: 'Chennai',
        email: 'library@iitm.ac.in',
        tier: 'tier1',
        libraryName: 'Central Library',
        contactPerson: 'Dr. Rajesh Kumar',
        phone: '+91-44-2257-8200',
      },
      {
        name: 'Osmania University',
        code: 'OU',
        state: 'Telangana',
        city: 'Hyderabad',
        email: 'library@osmania.ac.in',
        tier: 'tier2',
        libraryName: 'Main Library',
        contactPerson: 'Prof. Anita Singh',
        phone: '+91-40-2768-6666',
      },
      {
        name: 'Vidyasagar University',
        code: 'VU',
        state: 'West Bengal',
        city: 'Medinipur',
        email: 'library@vidyasagar.ac.in',
        tier: 'tier3',
        libraryName: 'Digital Library',
        contactPerson: 'Ms. Priya Sharma',
        phone: '+91-3222-275-500',
      },
      {
        name: 'Delhi University',
        code: 'DU',
        state: 'Delhi',
        city: 'New Delhi',
        email: 'library@du.ac.in',
        tier: 'tier1',
        libraryName: 'North Campus Library',
        contactPerson: 'Prof. Vikram Gupta',
        phone: '+91-11-2766-5555',
      },
      {
        name: 'Jadavpur University',
        code: 'JU',
        state: 'West Bengal',
        city: 'Kolkata',
        email: 'library@jadavpur.ac.in',
        tier: 'tier2',
        libraryName: 'Jadavpur Memorial Library',
        contactPerson: 'Dr. Amitabha Dey',
        phone: '+91-33-2414-6666',
      },
      {
        name: 'Anna University',
        code: 'AU',
        state: 'Tamil Nadu',
        city: 'Chennai',
        email: 'library@annauniv.edu.in',
        tier: 'tier2',
        libraryName: 'University Library',
        contactPerson: 'Ms. Kavya Raman',
        phone: '+91-44-2249-4000',
      },
      {
        name: 'Banaras Hindu University',
        code: 'BHU',
        state: 'Uttar Pradesh',
        city: 'Varanasi',
        email: 'library@bhu.ac.in',
        tier: 'tier1',
        libraryName: 'Central Library',
        contactPerson: 'Prof. Ashok Mishra',
        phone: '+91-542-2361-000',
      },
      {
        name: 'University of Mumbai',
        code: 'MU',
        state: 'Maharashtra',
        city: 'Mumbai',
        email: 'library@mu.ac.in',
        tier: 'tier1',
        libraryName: 'Academic Library',
        contactPerson: 'Mr. Arjun Desai',
        phone: '+91-22-2650-4444',
      },
    ]);

    console.log(`Created ${colleges.length} colleges`);

    // Create books with ratings (rating reflects condition and availability)
    const books = await Book.insertMany([
      // Computer Science Books
      {
        title: 'Introduction to Algorithms',
        author: 'Thomas H. Cormen',
        isbn: '978-0-262-03384-8',
        description: 'A comprehensive introduction to algorithms. Excellent condition with good availability.',
        category: 'Computer Science',
        publisher: 'MIT Press',
        publishedYear: 2009,
        rating: 4.8,
        availability: { total: 15, available: 8 },
        college: colleges[0]._id,
      },
      {
        title: 'Database Systems',
        author: 'C. J. Date',
        isbn: '978-0-321-88471-7',
        description: 'Comprehensive guide to database design. Good condition, moderate availability.',
        category: 'Computer Science',
        publisher: 'Addison-Wesley',
        publishedYear: 2015,
        rating: 4.5,
        availability: { total: 12, available: 5 },
        college: colleges[0]._id,
      },
      {
        title: 'The C Programming Language',
        author: 'Brian W. Kernighan',
        isbn: '978-0-13-110362-7',
        description: 'The definitive guide to C programming. Excellent condition with high availability.',
        category: 'Computer Science',
        publisher: 'Prentice Hall',
        publishedYear: 1988,
        rating: 4.9,
        availability: { total: 8, available: 6 },
        college: colleges[0]._id,
      },
      {
        title: 'Data Structures and Algorithms',
        author: 'Mark Allen Weiss',
        isbn: '978-0-13-463599-3',
        description: 'In-depth coverage of data structures with practical examples. Good condition.',
        category: 'Computer Science',
        publisher: 'Addison-Wesley',
        publishedYear: 2012,
        rating: 4.6,
        availability: { total: 14, available: 9 },
        college: colleges[3]._id,
      },
      {
        title: 'Design Patterns',
        author: 'Gang of Four',
        isbn: '978-0-201-63361-0',
        description: 'Elements of reusable object-oriented software. Limited availability, well-maintained.',
        category: 'Computer Science',
        publisher: 'Addison-Wesley',
        publishedYear: 1994,
        rating: 4.7,
        availability: { total: 7, available: 3 },
        college: colleges[1]._id,
      },
      {
        title: 'Operating Systems Concepts',
        author: 'Abraham Silberschatz',
        isbn: '978-1-118-06333-0',
        description: 'Comprehensive coverage of operating systems principles. Fair condition.',
        category: 'Computer Science',
        publisher: 'Wiley',
        publishedYear: 2012,
        rating: 4.6,
        availability: { total: 11, available: 7 },
        college: colleges[5]._id,
      },
      {
        title: 'Computer Networks',
        author: 'Andrew S. Tanenbaum',
        isbn: '978-0-13-359535-9',
        description: 'Principles, protocols, and practice. Well-maintained copies.',
        category: 'Computer Science',
        publisher: 'Prentice Hall',
        publishedYear: 2010,
        rating: 4.6,
        availability: { total: 10, available: 6 },
        college: colleges[6]._id,
      },
      {
        title: 'Artificial Intelligence: A Modern Approach',
        author: 'Stuart Russell',
        isbn: '978-0-13-604259-4',
        description: 'Comprehensive overview of AI concepts. Good condition, limited copies.',
        category: 'Computer Science',
        publisher: 'Pearson',
        publishedYear: 2020,
        rating: 4.7,
        availability: { total: 9, available: 5 },
        college: colleges[2]._id,
      },
      {
        title: 'Web Development with Node.js',
        author: 'Tom Jelen',
        isbn: '978-1-492-05303-1',
        description: 'Modern web development techniques. Fair condition.',
        category: 'Computer Science',
        publisher: 'O\'Reilly',
        publishedYear: 2021,
        rating: 4.4,
        availability: { total: 6, available: 4 },
        college: colleges[4]._id,
      },
      {
        title: 'Software Architecture Patterns',
        author: 'Mark Richards',
        isbn: '978-1-491-92141-4',
        description: 'Understanding software architecture approaches. Good availability.',
        category: 'Computer Science',
        publisher: 'O\'Reilly',
        publishedYear: 2015,
        rating: 4.5,
        availability: { total: 8, available: 5 },
        college: colleges[1]._id,
      },

      // Physics Books
      {
        title: 'Physics for Scientists and Engineers',
        author: 'Serway & Jewett',
        isbn: '978-1-305-26002-4',
        description: 'Modern physics textbook with practical applications. Excellent collection, high availability.',
        category: 'Physics',
        publisher: 'Cengage Learning',
        publishedYear: 2018,
        rating: 4.7,
        availability: { total: 20, available: 12 },
        college: colleges[1]._id,
      },
      {
        title: 'Quantum Mechanics',
        author: 'David J. Griffiths',
        isbn: '978-1-107-17986-8',
        description: 'Introduction to quantum mechanics. Good condition, some copies available.',
        category: 'Physics',
        publisher: 'Cambridge University Press',
        publishedYear: 2016,
        rating: 4.7,
        availability: { total: 9, available: 5 },
        college: colleges[4]._id,
      },
      {
        title: 'Classical Mechanics',
        author: 'Joseph L. Goldstein',
        isbn: '978-0-13-165973-4',
        description: 'Advanced mechanics concepts. Limited availability.',
        category: 'Physics',
        publisher: 'Pearson',
        publishedYear: 2014,
        rating: 4.6,
        availability: { total: 7, available: 4 },
        college: colleges[6]._id,
      },
      {
        title: 'Optics',
        author: 'Eugene Hecht',
        isbn: '978-0-13-515571-7',
        description: 'Comprehensive optics and photonics reference. Fair condition.',
        category: 'Physics',
        publisher: 'Pearson',
        publishedYear: 2017,
        rating: 4.5,
        availability: { total: 8, available: 5 },
        college: colleges[3]._id,
      },
      {
        title: 'Thermodynamics and Statistical Mechanics',
        author: 'F. Reif',
        isbn: '978-0-07-051100-1',
        description: 'Fundamental principles with detailed explanations. Limited copies.',
        category: 'Physics',
        publisher: 'McGraw-Hill',
        publishedYear: 1965,
        rating: 4.6,
        availability: { total: 6, available: 3 },
        college: colleges[0]._id,
      },

      // Mathematics Books
      {
        title: 'Calculus and Analytical Geometry',
        author: 'George B. Thomas',
        isbn: '978-0-321-68398-8',
        description: 'Fundamental mathematics for engineers. High availability, excellent condition.',
        category: 'Mathematics',
        publisher: 'Pearson',
        publishedYear: 2012,
        rating: 4.4,
        availability: { total: 25, available: 18 },
        college: colleges[1]._id,
      },
      {
        title: 'Linear Algebra',
        author: 'David C. Lay',
        isbn: '978-0-13-467328-8',
        description: 'Linear algebra with applications and problem sets. Good availability.',
        category: 'Mathematics',
        publisher: 'Pearson',
        publishedYear: 2019,
        rating: 4.4,
        availability: { total: 16, available: 11 },
        college: colleges[3]._id,
      },
      {
        title: 'Discrete Mathematics and Its Applications',
        author: 'Kenneth H. Rosen',
        isbn: '978-0-07-338309-8',
        description: 'Comprehensive discrete mathematics textbook. Well-maintained collection.',
        category: 'Mathematics',
        publisher: 'McGraw-Hill',
        publishedYear: 2019,
        rating: 4.5,
        availability: { total: 13, available: 8 },
        college: colleges[4]._id,
      },
      {
        title: 'Abstract Algebra',
        author: 'David S. Dummit',
        isbn: '978-0-471-43334-7',
        description: 'Modern approach to abstract algebra theory. Limited copies.',
        category: 'Mathematics',
        publisher: 'Wiley',
        publishedYear: 2004,
        rating: 4.6,
        availability: { total: 5, available: 2 },
        college: colleges[2]._id,
      },
      {
        title: 'Real Analysis',
        author: 'Walter Rudin',
        isbn: '978-0-07-054234-1',
        description: 'Principle of mathematical analysis. Standard reference, fair availability.',
        category: 'Mathematics',
        publisher: 'McGraw-Hill',
        publishedYear: 1976,
        rating: 4.7,
        availability: { total: 7, available: 4 },
        college: colleges[5]._id,
      },

      // Chemistry Books
      {
        title: 'Organic Chemistry',
        author: 'Paula Y. Bruice',
        isbn: '978-0134042755',
        description: 'Comprehensive organic chemistry resource. Some copies available.',
        category: 'Chemistry',
        publisher: 'Pearson',
        publishedYear: 2016,
        rating: 4.3,
        availability: { total: 10, available: 4 },
        college: colleges[2]._id,
      },
      {
        title: 'General Chemistry',
        author: 'Darrell Ebbing',
        isbn: '978-1-133-61066-8',
        description: 'Fundamental principles of chemistry. Good availability.',
        category: 'Chemistry',
        publisher: 'Cengage Learning',
        publishedYear: 2013,
        rating: 4.3,
        availability: { total: 18, available: 12 },
        college: colleges[5]._id,
      },
      {
        title: 'Organic Synthesis',
        author: 'Michael B. Smith',
        isbn: '978-0-12-415894-8',
        description: 'Strategies and control in organic synthesis. Limited copies.',
        category: 'Chemistry',
        publisher: 'Elsevier',
        publishedYear: 2010,
        rating: 4.4,
        availability: { total: 6, available: 2 },
        college: colleges[2]._id,
      },
      {
        title: 'Physical Chemistry',
        author: 'Peter Atkins',
        isbn: '978-0-19-875444-6',
        description: 'Quantitative approach to chemical phenomena. Good condition.',
        category: 'Chemistry',
        publisher: 'Oxford University Press',
        publishedYear: 2019,
        rating: 4.6,
        availability: { total: 8, available: 5 },
        college: colleges[4]._id,
      },
      {
        title: 'Inorganic Chemistry',
        author: 'Mark Weller',
        isbn: '978-0-19-862612-5',
        description: 'Principles and practice of inorganic chemistry. Fair availability.',
        category: 'Chemistry',
        publisher: 'Oxford University Press',
        publishedYear: 2014,
        rating: 4.5,
        availability: { total: 7, available: 4 },
        college: colleges[1]._id,
      },

      // Engineering Books
      {
        title: 'Mechanics of Materials',
        author: 'Ferdinand P. Beer',
        isbn: '978-0-07-015219-9',
        description: 'Analysis and design of structures. Good condition.',
        category: 'Engineering',
        publisher: 'McGraw-Hill',
        publishedYear: 2014,
        rating: 4.5,
        availability: { total: 12, available: 8 },
        college: colleges[7]._id,
      },
      {
        title: 'Electric Circuits',
        author: 'James W. Nilsson',
        isbn: '978-0-13-376001-2',
        description: 'Analysis and design of electronic circuits. Latest edition.',
        category: 'Engineering',
        publisher: 'Pearson',
        publishedYear: 2020,
        rating: 4.6,
        availability: { total: 14, available: 9 },
        college: colleges[7]._id,
      },
      {
        title: 'Control Systems Engineering',
        author: 'Norman S. Nise',
        isbn: '978-1-119-46636-3',
        description: 'Practical approach to control system design. Good availability.',
        category: 'Engineering',
        publisher: 'Wiley',
        publishedYear: 2019,
        rating: 4.5,
        availability: { total: 9, available: 5 },
        college: colleges[3]._id,
      },
      {
        title: 'Heat Transfer',
        author: 'Michael F. Ashby',
        isbn: '978-0-08-099999-8',
        description: 'Principles and applications in thermal engineering. Fair condition.',
        category: 'Engineering',
        publisher: 'Butterworth-Heinemann',
        publishedYear: 2016,
        rating: 4.4,
        availability: { total: 7, available: 4 },
        college: colleges[6]._id,
      },

      // Biology Books
      {
        title: 'Biology: The Dynamic Science',
        author: 'Peter Raven',
        isbn: '978-1-305-35820-2',
        description: 'Modern biology principles and concepts. Extensive collection, high availability.',
        category: 'Biology',
        publisher: 'Cengage Learning',
        publishedYear: 2017,
        rating: 4.4,
        availability: { total: 19, available: 14 },
        college: colleges[6]._id,
      },
      {
        title: 'Molecular Biology of the Gene',
        author: 'James D. Watson',
        isbn: '978-0-13-404740-2',
        description: 'Molecular mechanisms and cellular functions. Good condition.',
        category: 'Biology',
        publisher: 'Pearson',
        publishedYear: 2020,
        rating: 4.6,
        availability: { total: 11, available: 7 },
        college: colleges[4]._id,
      },
      {
        title: 'Ecological Principles',
        author: 'Paul R. Ehrlich',
        isbn: '978-0-87547-013-0',
        description: 'Ecosystem science and conservation biology. Limited copies.',
        category: 'Biology',
        publisher: 'Macmillan',
        publishedYear: 2008,
        rating: 4.3,
        availability: { total: 6, available: 3 },
        college: colleges[5]._id,
      },
      {
        title: 'Cell Biology',
        author: 'Thomas D. Pollard',
        isbn: '978-0-393-88468-8',
        description: 'Comprehensive cell biology and molecular processes. Fair condition.',
        category: 'Biology',
        publisher: 'W. W. Norton',
        publishedYear: 2016,
        rating: 4.5,
        availability: { total: 8, available: 5 },
        college: colleges[2]._id,
      },
    ]);

    console.log(`Created ${books.length} books`);

    // Create users - save individually to trigger password hashing pre-hook
    const usersData = [
      // IITM Users
      {
        email: 'raj.kumar@iitm.student.ac.in',
        name: 'Raj Kumar',
        password: 'Password123',
        role: 'student',
        college: colleges[0]._id,
        isActive: true,
      },
      {
        email: 'priya.sharma@iitm.student.ac.in',
        name: 'Priya Sharma',
        password: 'Password123',
        role: 'student',
        college: colleges[0]._id,
        isActive: true,
      },
      {
        email: 'arjun.menon@iitm.student.ac.in',
        name: 'Arjun Menon',
        password: 'Password123',
        role: 'student',
        college: colleges[0]._id,
        isActive: true,
      },
      {
        email: 'sneha.patel@iitm.student.ac.in',
        name: 'Sneha Patel',
        password: 'Password123',
        role: 'student',
        college: colleges[0]._id,
        isActive: true,
      },
      {
        email: 'librarian@iitm.ac.in',
        name: 'Librarian IITM',
        password: 'LibrarianPass123',
        role: 'librarian',
        college: colleges[0]._id,
        isActive: true,
      },

      // Osmania University Users
      {
        email: 'aditya.patel@ou.student.ac.in',
        name: 'Aditya Patel',
        password: 'Password123',
        role: 'student',
        college: colleges[1]._id,
        isActive: true,
      },
      {
        email: 'ananya.desai@ou.student.ac.in',
        name: 'Ananya Desai',
        password: 'Password123',
        role: 'student',
        college: colleges[1]._id,
        isActive: true,
      },
      {
        email: 'bharath.reddy@ou.student.ac.in',
        name: 'Bharath Reddy',
        password: 'Password123',
        role: 'student',
        college: colleges[1]._id,
        isActive: true,
      },
      {
        email: 'meera.kapoor@ou.student.ac.in',
        name: 'Meera Kapoor',
        password: 'Password123',
        role: 'student',
        college: colleges[1]._id,
        isActive: true,
      },
      {
        email: 'librarian@osmania.ac.in',
        name: 'Head Librarian OU',
        password: 'LibrarianPass123',
        role: 'librarian',
        college: colleges[1]._id,
        isActive: true,
      },

      // Vidyasagar University Users
      {
        email: 'rohan.gupta@vu.student.ac.in',
        name: 'Rohan Gupta',
        password: 'Password123',
        role: 'student',
        college: colleges[2]._id,
        isActive: true,
      },
      {
        email: 'neha.singh@vu.student.ac.in',
        name: 'Neha Singh',
        password: 'Password123',
        role: 'student',
        college: colleges[2]._id,
        isActive: true,
      },
      {
        email: 'gaurav.kumar@vu.student.ac.in',
        name: 'Gaurav Kumar',
        password: 'Password123',
        role: 'student',
        college: colleges[2]._id,
        isActive: true,
      },
      {
        email: 'pooja.gupta@vu.student.ac.in',
        name: 'Pooja Gupta',
        password: 'Password123',
        role: 'student',
        college: colleges[2]._id,
        isActive: true,
      },
      {
        email: 'librarian@vidyasagar.ac.in',
        name: 'Library Manager VU',
        password: 'LibrarianPass123',
        role: 'librarian',
        college: colleges[2]._id,
        isActive: true,
      },

      // Delhi University Users
      {
        email: 'amit.verma@du.student.ac.in',
        name: 'Amit Verma',
        password: 'Password123',
        role: 'student',
        college: colleges[3]._id,
        isActive: true,
      },
      {
        email: 'pooja.nair@du.student.ac.in',
        name: 'Pooja Nair',
        password: 'Password123',
        role: 'student',
        college: colleges[3]._id,
        isActive: true,
      },
      {
        email: 'aryan.singh@du.student.ac.in',
        name: 'Aryan Singh',
        password: 'Password123',
        role: 'student',
        college: colleges[3]._id,
        isActive: true,
      },
      {
        email: 'divya.iyer@du.student.ac.in',
        name: 'Divya Iyer',
        password: 'Password123',
        role: 'student',
        college: colleges[3]._id,
        isActive: true,
      },
      {
        email: 'librarian@du.ac.in',
        name: 'Chief Librarian DU',
        password: 'LibrarianPass123',
        role: 'librarian',
        college: colleges[3]._id,
        isActive: true,
      },

      // Jadavpur University Users
      {
        email: 'vivek.chakraborty@ju.student.ac.in',
        name: 'Vivek Chakraborty',
        password: 'Password123',
        role: 'student',
        college: colleges[4]._id,
        isActive: true,
      },
      {
        email: 'shruti.roy@ju.student.ac.in',
        name: 'Shruti Roy',
        password: 'Password123',
        role: 'student',
        college: colleges[4]._id,
        isActive: true,
      },
      {
        email: 'soumen.das@ju.student.ac.in',
        name: 'Soumen Das',
        password: 'Password123',
        role: 'student',
        college: colleges[4]._id,
        isActive: true,
      },
      {
        email: 'riya.banerjee@ju.student.ac.in',
        name: 'Riya Banerjee',
        password: 'Password123',
        role: 'student',
        college: colleges[4]._id,
        isActive: true,
      },
      {
        email: 'librarian@jadavpur.ac.in',
        name: 'Library Director JU',
        password: 'LibrarianPass123',
        role: 'librarian',
        college: colleges[4]._id,
        isActive: true,
      },

      // Anna University Users
      {
        email: 'vikram.krishnan@au.student.ac.in',
        name: 'Vikram Krishnan',
        password: 'Password123',
        role: 'student',
        college: colleges[5]._id,
        isActive: true,
      },
      {
        email: 'deepa.reddy@au.student.ac.in',
        name: 'Deepa Reddy',
        password: 'Password123',
        role: 'student',
        college: colleges[5]._id,
        isActive: true,
      },
      {
        email: 'karthik.devi@au.student.ac.in',
        name: 'Karthik Devi',
        password: 'Password123',
        role: 'student',
        college: colleges[5]._id,
        isActive: true,
      },
      {
        email: 'lakshmi.naidu@au.student.ac.in',
        name: 'Lakshmi Naidu',
        password: 'Password123',
        role: 'student',
        college: colleges[5]._id,
        isActive: true,
      },
      {
        email: 'librarian@annauniv.edu.in',
        name: 'Senior Librarian AU',
        password: 'LibrarianPass123',
        role: 'librarian',
        college: colleges[5]._id,
        isActive: true,
      },

      // Banaras Hindu University Users
      {
        email: 'ravi.singh@bhu.student.ac.in',
        name: 'Ravi Singh',
        password: 'Password123',
        role: 'student',
        college: colleges[6]._id,
        isActive: true,
      },
      {
        email: 'kavya.bansal@bhu.student.ac.in',
        name: 'Kavya Bansal',
        password: 'Password123',
        role: 'student',
        college: colleges[6]._id,
        isActive: true,
      },
      {
        email: 'vikrant.yadav@bhu.student.ac.in',
        name: 'Vikrant Yadav',
        password: 'Password123',
        role: 'student',
        college: colleges[6]._id,
        isActive: true,
      },
      {
        email: 'anushka.tiwari@bhu.student.ac.in',
        name: 'Anushka Tiwari',
        password: 'Password123',
        role: 'student',
        college: colleges[6]._id,
        isActive: true,
      },
      {
        email: 'librarian@bhu.ac.in',
        name: 'Head of Library BHU',
        password: 'LibrarianPass123',
        role: 'librarian',
        college: colleges[6]._id,
        isActive: true,
      },

      // University of Mumbai Users
      {
        email: 'sanjay.bhatt@mu.student.ac.in',
        name: 'Sanjay Bhatt',
        password: 'Password123',
        role: 'student',
        college: colleges[7]._id,
        isActive: true,
      },
      {
        email: 'isha.malhotra@mu.student.ac.in',
        name: 'Isha Malhotra',
        password: 'Password123',
        role: 'student',
        college: colleges[7]._id,
        isActive: true,
      },
      {
        email: 'harsh.pandey@mu.student.ac.in',
        name: 'Harsh Pandey',
        password: 'Password123',
        role: 'student',
        college: colleges[7]._id,
        isActive: true,
      },
      {
        email: 'nisha.joshi@mu.student.ac.in',
        name: 'Nisha Joshi',
        password: 'Password123',
        role: 'student',
        college: colleges[7]._id,
        isActive: true,
      },
      {
        email: 'librarian@mu.ac.in',
        name: 'Chief Librarian MU',
        password: 'LibrarianPass123',
        role: 'librarian',
        college: colleges[7]._id,
        isActive: true,
      },

      // Global Admin
      {
        email: 'admin@libris-connect.ac.in',
        name: 'System Administrator',
        password: 'AdminPass123',
        role: 'admin',
        college: colleges[0]._id,
        isActive: true,
      },
    ];

    // Create users individually to trigger password hashing pre-save hook
    const users = [];
    for (const userData of usersData) {
      const user = new User(userData);
      await user.save();
      users.push(user);
    }

    console.log(`Created ${users.length} users`);
    console.log('✓ Database seeded successfully');
    console.log('\nSample Logins:');
    console.log('  Student: raj.kumar@iitm.student.ac.in / Password123');
    console.log('  Librarian: librarian@iitm.ac.in / LibrarianPass123');
    console.log('  Admin: admin@libris-connect.ac.in / AdminPass123');

    await mongoose.connection.close();
  } catch (error) {
    console.error('✗ Seeding failed:', error);
    process.exit(1);
  }
};

seedDatabase();
